[package]
name = "midigrep"
version = "0.1.0"
authors = ["Jonas Hagstedt <hagstedt@gmail.com>"]

[profile.release]
lto = true  
panic = 'abort'

[dependencies]
nom-midi = "0.2.0"
nom = "2.2.1"
walkdir = "2"
rayon = "0.8.2"
docopt = "0.8.1"
serde= "1.0.16"
serde_derive = "1.0.16"
